#!/bin/bash
echo --------------------------- SSH INTO BBB: debian@192.168.137.1 ---------------------------

if [[ $1 = drive ]]
then
sshpass -p temppwd ssh -T debian@192.168.137.1 <<EOL
    sleep 2
    cd rcPWM/
    python3 drive.py --log DEBUG
EOL
fi

if [[ $1 = kill ]]
then
sshpass -p temppwd ssh -T debian@192.168.137.1 <<EOL
    clear
    lsof -ti :60006 | xargs kill -9
EOL
fi

sshpass -p 'temppwd' ssh -t debian@192.168.137.1 'cd rcPWM ; bash --login'
export SSHPASS='temppwd'
sshpass -e ssh -t debian@192.168.137.1 "CDTO=rcPWM exec bash --login"
