#!/bin/bash
echo --------------------------- SSH INTO BBB: debian@192.168.137.1 ---------------------------

if [[ $1 = connect ]]
then
	sshpass -p temppwd ssh debian@192.168.137.1 
fi
if [[ $1 = drive ]]
then
sshpass -p temppwd ssh -T debian@192.168.137.1 <<EOL
    sleep 2
    cd rcPWM/
    python3 drive.py
EOL
fi